config/routes.rb
  BShulim::Application.routes.draw do
  get "pages/info"
  resources :recipes

  root :to => redirect('recipes')

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :content, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_image(image_path, target_link, image_options, link_options={})
	  link_to(image_tag(image_path, image_options), target_link, link_options)
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BShulim</title>
  <link href='http://railsgirls.co.il/bootstrap/css/bootstrap.css' rel='stylesheet'>
  <link href='http://railsgirls.co.il/bootstrap/css/bootstrap-theme.css' rel='stylesheet'>
  <link href='http://getbootstrap.com/examples/offcanvas/offcanvas.js' rel='stylesheet'>
  <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
    <a class='navbar-brand' href='/'>Bishulim app</a>
    <ul class='nav navbar-nav'>
      <li class='active'>
        <a href='/recipes'>Recipes</a>
      </li>
    </ul>
  </div>
</nav>
<div class='container'>
<%= yield %>
</div>

</body>
</html>

app/views/pages/info.html.erb
<h1>About me</h1>
<p>Tamar Shouker</p>
<%= image_tag("tamar.jpg", :width => 200) %>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>מתכון </h4>
    <%= f.text_field :name, :cols => "90", :rows => "10", :wrap => "hard" %>
  </div>
  <div class="field" text-align="start">
    <h4>מרכיבים</h4>
    <%= f.text_area :ingredients, :cols => "90", :rows => "10", :wrap => "hard" %>
  </div>
  <div class="field">
    <h4>שלבי ההכנה</h4>
    <%= f.text_area :content, :cols => "90", :rows => "10", :wrap => "hard"%>
  </div>
  <div class="field">
    <h4>תמונה</h4>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="container">

  <div class="col-xs-12 col-sm-12">
    <p class="pull-right visible-xs">
      <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
    </p>
    <div class="jumbotron">
      <h1 align="center">בישולים</h1>
    </div>
    <div class="row">
      <% @recipes.each do |recipe| %>
        <div class="col-7 col-sm-7 col-lg-4">
          <h2 align="center"><%= link_to(recipe.name, recipe) %></h2>
          <p><%= link_to_image(recipe.picture_url, recipe, {:height => 200, class: 'img-circle'}, {}) if recipe.picture? %></p>
          <td>
            <%= link_to edit_recipe_path(recipe), class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
          <% end %>
          </td>
          <td>
            <%= link_to recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </div><!--/span-->
      <% end %>
     
    </div><!--/row-->
  </div><!--/span-->
</div><!--/.container-->

<br>
<%= link_to new_recipe_path, class: 'btn btn-default btn-lg' do %>
  <span class="glyphicon glyphicon-plus"></span>
  מתכון חדש
<% end %>
      

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong><%= @recipe.name %></strong>
</h1>

<p>
<h4>
  <strong>אבא תקנה בסופר</strong>
  <%= simple_format @recipe.ingredients %>
</h4>
</p>

<p>
<h4>
  <strong>אוקיי, מה עכשיו?</strong>
  <%= simple_format @recipe.content %>
</h4>
</p>

<p>
  <%= image_tag(@recipe.picture_url, :width => 600) if @recipe.picture.present? %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>